### ISSUE TITLE
How can I test this?

### ISSUE THREAD

**Issue by alan-andrade** [alphapeter/socket.io-express#1]
Hey, I'm writing an app in which I give the user a session once it hits the '/' path.
When the socket.io connects to the server in a web browser environment, everything looks good. Cookies are transmitted to the Auth handshake data. Great! now... how can I test this?

I'm using socket.io-client and when I connect to my app, the handshake data has no cookies :(

I tried using supertest implementing something similar to this:

```
request(app)
  .get('/')
  .end(function(err, res){
      io.on('connection', //blah)
});
```

Noup. It doesn't send the cookies. And I can se why. Socket.IO connect doesn't know who's connecting. At least with this piece of code.

Is there a way of injecting the cooke from the response header ?

Or any other better idea ?

**Comment by alphapeter** [comment]
You would probably not want to put the io.on('connect', func) within the end of a request. It should be initiated only once.

Besides from that, I should have made the socket io auth function more general, now it is configured for working with everyauth. It should be mentioned that the express middle ware authentification has to set session.auth.loggedIn to verify a successful socket.io authentification.

You need to have an express middleware for the authentification before this socket io auth function will work.

**Comment by alan-andrade** [comment]
I'm a bit confused now.

I'm using a logger middleware to keep track of every request. I was hoping that when io.connect() got connected, I'd receive some kind of log. I have nothing. With this in mind, If I implement an authentication m.w. looks it won't work.

It's very important to notice that all of this is being run in a test environment. When I use the browser everything works fine. So I guess this is more a should-I-be-using-socket.io-client question. Does this makes sense ?

Thanks in advance.
